# Generated by Django 3.2.7 on 2021-09-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watering',
            old_name='type',
            new_name='watering_type',
        ),
    ]
